### ISSUE TITLE
Do you really calculate CPU utilization?

### ISSUE THREAD

**Issue by pixelsebi** [mesosphere/marathon-autoscale#1]
Hey, I've just read the code and I am a bit confused by the fact, that you write:

`max_cpu_time = int(input("Enter the Max percent of CPU Usage averaged across all Application Instances to trigger Autoscale (ie. 80) : "))`

... but you actually just sum up the system/user CPU seconds and don't really calculate any percentage of CPU utilization?

`cpus_time =(task_stats['cpus_system_time_secs']+task_stats['cpus_user_time_secs'])`

So right now setting the `max_cpu_time` is not a percentage but a total value, which just gets averaged over all tasks?

`app_avg_cpu = (sum(app_cpu_values) / len(app_cpu_values))`

Or do I understand something wrong?

**Comment by navidurrahman** [comment]
I'm also trying to understand same thing. In my case, it always give me more than 1000.

@tkrausjr

**Comment by debashis-das** [comment]
Hey,
I am also trying to understand this in my case : 
`"statistics": {
        "cpus_limit": 2.1,
        "cpus_system_time_secs": 5.62,
        "cpus_user_time_secs": 91.03,
        "mem_limit_bytes": 2181038080,
        "mem_rss_bytes": 934060032
    }`
so the `cpus_time =(task_stats['cpus_system_time_secs']+task_stats['cpus_user_time_secs'])` comes to be 96.65 which is almost close to 100. So it is automatically scaling when we give 'or' for scaling with `Enter the Max percent of CPU Usage averaged across all Application Instances to trigger Autoscale (ie. 80) : 75`

With this calculation it doesn't give the % utilization of CPU. It only sums up cpus time. So can anybody provide with a proper formula to calculate CPU time using this statistics? 

Thanks in advance

**Comment by denisbetsi** [comment]
It's not the utilization as in current reading. It's amount of time it spent running those functions. The method of using CPU as a metric is flawed. Only one that can be used somewhat reliably is Memory utilization.

Only thing available is within Docker API which would contain enough data to determine current cpu % utilization not Mesos stats api.

**Comment by tkrausjr** [comment]
Thats correct @pixelsebi & @debashis-das. The Mesos metrics just uses native linux counters your would find in /proc and the CPU metric is just time based. There is a way I could do a rough utilization calculation if I make some assumptions.... This was done quickly as a demo prove what is possible but much more work is needed. I cant use the Docker API because with MEsos there are other Containerizers that can be used besides Docker. Going to spend some more time on this in next few weeks.

**Comment by denisbetsi** [comment]
@tkrausjr the other thing is logic on getting CPU utilization. Currently even if use of an app goes down, the reading on CPU utilization doesn't go down and remains the same number, only time that number changes is when use goes up so the reading would show a high number, that throws the rest of the average logic out of the window.

It will lets say use CPU utilization at 140. Scale up, new instance has lets say utilization of 10. Currently it takes 10 + 140 and / 2 = 75, if you have utilization set to 50% then scale up, it launches another instance and scales up to lets say 3 units, then it's 140 + 10 + 10 / 3 = 50.33 which is still higher than 50% then it scales it up again. Now you end up with 3 instances, 2 are barely used and if usage goes up from 10 to 20, then it wants to scale up and up. It should be doing Median vs Avg calculation.

The the other issue is that it's using Mesos API, the CPU utilization numbers although time based, take that reading from Nanoseconds and for some odd reason, someone though of taking such a sensitive counter from nano seconds to Seconds, thus whipping out useful information.

If Mesos API had put in an original Nanosecond reading, then this CPU metric of this tool would become functional.

**Comment by gpetrousov** [comment]
Hello everyone
I pushed an update to a new branch where I calculate CPU percentage.
The results I'm getting are very close to docker stats command which reads cgroups directly.
With this addition you can input average desired CPU percentage across containers which will determine the scaling.

A future TODO would be to divide the calculated percentage by the number of cores on the system.
This might be necessary for some, because as with docker stats command, the usage may be greater than 100% and this is because the usage is calculated as a sum for all cores. So when you see something like 224%, this means that the container is spread across 3 CPU cores.

I think one of you suggested reading a blog post from theza
https://theza.ch/2014/09/17/cpu-resources-in-docker-mesos-and-marathon/
This is a very good post and it did the research back when Marathon was returning the timings in nanoseconds, in this case the calculation would be
total_cpu_used = (float(cpu_time2 - cpu_time1) / 1000000000) / (timestamp2 - timestamp1) \* 100
I used to calculate the usage using Mesos API (5051) which IMHO was more accurate than Marathon.

@tkrausjr 
Please merge when possible

**Comment by tkrausjr** [comment]
@ gpetrousov  Thats awesome -  I will review this tonight and merge.

**Comment by tkrausjr** [comment]
Merged- Thanks.

**Comment by RahulBahl** [comment]
Hi Guys,

I was looking through the code and still see the below, and was wondering if I was missing something because when running the code it still outputs an average of time instead of the average percentage as proposed by @gpetrousov . Thanks.

`app_avg_cpu = (sum(app_cpu_values) / len(app_cpu_values))
 print ('Current Average  CPU Time for app', marathon_app, '=', app_avg_cpu)`

Regards,
Rahul

**Comment by gpetrousov** [comment]
@RahulBahl The values are calculated as average usage in percentage.
The print statement needs to be fixed to say something like
print ('Current average CPU usage for app :', marathon_app, '=', app_avg_cpu, "%")

**Comment by RahulBahl** [comment]
@gpetrousov Thanks for the update and sorry for the trouble, realized that while looking at it fresh this morning.
